### ISSUE TITLE
UGen is not recognized on Windows 10

### ISSUE THREAD

**Issue by gantz-giraffe** [supercollider/cookiecutter-supercollider-plugin#1]
I managed to get this built via cookiecutter and cmake on Windows 10, copied the \simplegain\build\install\SimpleGain\SimpleGain folder into my extensions directory (AppData\Local\SuperCollider\Extensions,), but upon trying to use it SC produces the error

    exception in GraphDef_Recv: UGen 'SimpleGain' not installed.
    *** ERROR: SynthDef temp__0 not found
    FAILURE IN SERVER /s_new SynthDef not found

**Comment by gantz-giraffe** [comment]
Just realized the problem. I thought that Windows externals were supposed to be able to work with .dll extension, from what I read in the "Writing Unit Generators" article in the official Supercollider documentation. This is not the case; they must be _compiled_ as a dll, but the visible extension needs to be .scx in order for SC to recognize them. The Visual Studio build generated by cmake doesn't take that nuance into account, but it works if you manually rename the extension post-compilation.

**Comment by mossheim** [comment]
@gantz-giraffe thanks for the report. Manual rename should not be required; I believe a current PR in SC fixes this.
