### ISSUE TITLE
[FR] set default SC source location from cookiecutter input

### ISSUE THREAD

**Issue by mtmccrea** [supercollider/cookiecutter-supercollider-plugin#13]
If you're building your UGen in a location that is **not** at `../supercollider`, or if your clone of the sc source is not called "supercollider" (I have a few versions), the simple default Cmake command in the readme won't work:
```
$ cd simplegain
$ mkdir build
$ cd build
$ cmake .. -DCMAKE_BUILD_TYPE=Debug
$ cmake --build . --config Debug
```

This is easy enough to work around, just add the `-DSC_PATH` flag. But given that the project was built with cookiecutter, and the path was already entered in the questionnaire used to set up the project, I'm hoping this path can be set as the [default sc path](https://github.com/supercollider/supercollider/blob/63783aeca007c1e1d2a7cf73b3f3da056913f077/tools/cmake_gen/SuperColliderServerPlugin.cmake#L9).

I looked around and couldn't quite figure out if/how this might be possible.

**Comment by mossheim** [comment]
This is a case where being inflexible leads to better interoperability, so I will not change this.
