### ISSUE TITLE
AppVeyor fails to build

### ISSUE THREAD

**Issue by woolgathering** [supercollider/cookiecutter-supercollider-plugin#17]
AppVeyor fails to find SCVersion.txt despite being finding the correct directory for SuperCollider:

```
mkdir build
cd build
cmake -G "%CMAKE_GENERATOR%" -DSC_PATH=../supercollider -DCMAKE_INSTALL_PREFIX=_install ..
-- Found SuperCollider: C:/projects/supercollider
CMake Error at CMakeLists.txt:34 (include):
  include could not find load file:

    C:/projects/simplegain/supercollider/SCVersion.txt

```

Got around it by adding a softlink to supercollider/ in the project directory but I don't know enough about AppVeyor to deal with it properly.

**Comment by mossheim** [comment]
thank you, could you please submit a patch? I will not be able to look at this for quite a while. no knowledge of appveyor necessary, it looks like cmake is simply constructing the wrong path when it searches for SCVersion.txt.

**Comment by mossheim** [comment]
Have pushed a fix for this at https://github.com/supercollider/supercollider/pull/4668
