### ISSUE TITLE
Repo status: fork or not?

### ISSUE THREAD

**Issue by dyfer** [supercollider/cookiecutter-supercollider-plugin#24]
This repo is still listed as a fork of @brianlheim - AFAIU it should function as the "main" repo (correct me if I'm wrong).
This causes only minor issues AFAICT - e.g. when directly cloning this repo in github desktop, it would add "upstream" remote pointing to @brianlheim 's repo.

I don't know how to change this (if the change is indeed desired).

**Comment by mossheim** [comment]
AFAIK it can't be changed without deleting one of the repos. i don't want to delete my fork (yet).
